server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/UrbanMarket
    web:
      pageable:
        default-page-size: 4
        max-page-size: 50

  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

dropbox:
  app-key: ${DROPBOX_APP_KEY}
  app-secret: ${DROPBOX_APP_SECRET}