server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/UrbanMarket



  mail:
    host: smtp.gmail.com
    username: kasmatuy2k17@gmail.com
    password: eyqp ekjx nqzq zccd
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
