server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/UrbanMarket



  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
